version: '3.9'
services:
  nodea:
    build: .
    command: ["--id","A","--addr",":8091","--peers","http://nodeb:8092,http://nodec:8093,http://noded:8094","--validators","A,B,C,D"]
    ports: ["8091:8091"]
    environment:
      - PEER_TOKEN=t
      - LEADER_URL=http://nodea:8091
      - IS_LEADER=true
      # Demo dev key (do not use in prod)
      - ETH_PRIVATE_KEY=0xb71c71a67e1177ad4e901695e1b4b9c2d68e8f0e2b8a9d17a2a4d4a8e6f5f2f0
      - MTM_BASE_URL=http://host.docker.internal:8081
      - BESU_RPC_URL=http://besu-dev.sirt-xfsc.click:8545
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nodeb:
    build: .
    command: ["--id","B","--addr",":8092","--peers","http://nodea:8091,http://nodec:8093,http://noded:8094","--validators","A,B,C,D"]
    ports: ["8092:8092"]
    environment:
      - PEER_TOKEN=t
      - LEADER_URL=http://nodea:8091
      - IS_LEADER=false
      - ETH_PRIVATE_KEY=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
      - MTM_BASE_URL=http://host.docker.internal:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nodec:
    build: .
    command: ["--id","C","--addr",":8093","--peers","http://nodea:8091,http://nodeb:8092,http://noded:8094","--validators","A,B,C,D"]
    ports: ["8093:8093"]
    environment:
      - PEER_TOKEN=t
      - LEADER_URL=http://nodea:8091
      - IS_LEADER=false
      - ETH_PRIVATE_KEY=0x8f2a559490b8d6e3d2b1016da0fbdc3f5b6b6f9bcd3d2e2c2a2b1a1a0a9a8a7a
      - MTM_BASE_URL=http://host.docker.internal:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
  noded:
    build: .
    command: ["--id","D","--addr",":8094","--peers","http://nodea:8091,http://nodeb:8092,http://nodec:8093","--validators","A,B,C,D"]
    ports: ["8094:8094"]
    environment:
      - PEER_TOKEN=t
      - LEADER_URL=http://nodea:8091
      - IS_LEADER=false
      - ETH_PRIVATE_KEY=0x5c51f7b14a6b3c2e9d8a7f6e5d4c3b2a190817161514131211100f0e0d0c0b0a
      - MTM_BASE_URL=http://host.docker.internal:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
